# Use colors in coreutils utilities output
alias ls='ls --color=auto'
alias grep='grep --color'

# ls aliases
alias ll='ls -lah'
alias la='ls -A'
alias l='ls'

# Aliases to protect against overwriting
alias cp='cp -i'
alias mv='mv -i'

# Update dotfiles
dfu() {
    (
        cd ~/.dotfiles && git pull --ff-only && ./install -q
    )
}

# Create a directory and cd into it
mkcd() {
    mkdir -p "${1}" && cd "${1}"
}

# Imported from Bash
alias c='clear'
alias copy='xclip -selection clipboard'
alias g='git'
alias ga='git add'
alias gall='git add -A'
alias gap='git add -p'
alias gb='git branch'
alias gbD='git branch -D'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbm='git branch -m'
alias gbt='git branch --track'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcaa='git commit -a --amend -C HEAD'
alias gcam='git commit -v -am'
alias gcamd='git commit --amend'
alias gcb='git checkout -b'
alias gci='git commit --interactive'
alias gcl='git clone'
alias gclean='git clean -fd'
alias gcm='git commit -v -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gcpd='git checkout master; git pull; git branch -D'
alias gcpx='git cherry-pick -x'
alias gcsam='git commit -S -am'
alias gct='git checkout --track'
alias gd='git diff'
alias gdel='git branch -D'
alias gds='git diff --staged'
alias gdt='git difftool'
alias gdv='git diff -w "$@" | vim -R -'
alias get='git'
alias gexport='git archive --format zip --output'
alias gf='git fetch --all --prune'
alias gft='git fetch --all --prune --tags'
alias gftv='git fetch --all --prune --tags --verbose'
alias gfv='git fetch --all --prune --verbose'
alias gg='git log --graph --pretty=format:'\''%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset'\'' --abbrev-commit --date=relative'
alias ggs='gg --stat'
alias ggui='git gui'
alias gh='ghm'
alias ghm='cd "$(git rev-parse --show-toplevel)"'
alias gl='git pull'
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias glum='git pull upstream master'
alias gm='git merge'
alias gmu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias gmv='git mv'
alias gnew='git log HEAD@{1}..HEAD@{0}'
alias gp='git push'
alias gpatch='git format-patch -1'
alias gpo='git push origin HEAD'
alias gpom='git push origin master'
alias gpp='git pull && git push'
alias gpr='git pull --rebase'
alias gpristine='git reset --hard && git clean -dfx'
alias gprom='git fetch origin master && git rebase origin/master && git update-ref refs/heads/master origin/master'
alias gpu='git push --set-upstream'
alias gpunch='git push --force-with-lease'
alias gpuo='git push --set-upstream origin'
alias gpuoc='git push --set-upstream origin $(git symbolic-ref --short HEAD)'
alias gr='git remote'
alias gra='git remote add'
alias grb='git rebase'
alias grep='grep --color=auto'
alias grm='git rebase master'
alias grmi='git rebase master -i'
alias grv='git remote -v'
alias gs='git status'
alias gsh='git show'
alias gsl='git shortlog -sn'
alias gss='git status -s'
alias gst='git stash'
alias gstb='git stash branch'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstpo='git stash pop'
alias gstpu='git stash push'
alias gstpum='git stash push -m'
alias gsts='git stash push'
alias gstsm='git stash push -m'
alias gsu='git submodule update --init --recursive'
alias gsw='git switch'
alias gswc='git switch --create'
alias gswm='git switch master'
alias gswt='git switch --track'
alias gt='git tag'
alias gta='git tag -a'
alias gtd='git tag -d'
alias gtl='git tag -l'
alias gtls='git tag -l | sort -V'
alias gu='git ls-files . --exclude-standard --others'
alias gup='git fetch && git rebase'
alias gus='git reset HEAD'
alias gwc='git whatchanged'
alias h='history'
alias ipy='ipython'
alias k='clear'
alias l='ls -a'
alias l1='ls -1'
alias la='ls -AF'
alias ll='ls -al'
alias ls='ls --color=auto'
alias mv='mv -i'
alias copy='/usr/bin/xclip -selection clipboard'
alias paste='/usr/bin/xclip -selection clipboard -o'
alias q='exit'
alias rd='rmdir'
alias sc='systemctl'
alias sce='systemctl stop'
alias scr='systemctl daemon-reload'
alias scs='systemctl start'
alias scu='systemctl --user'
alias scue='systemctl --user stop'
alias scur='systemctl --user daemon-reload'
alias scus='systemctl --user start'
alias sl='ls'
alias dc='cd'
alias bc='bc -qil'
alias ip='ip --color --brief'

# User Aliases
alias sharescreen='shellshare --room savsingh --password $1'
