# Savitoj's config

- defaults:
    link:
      create: true
      relink: true

- clean:
  - '~'
  - '~/bin'

- shell:
  - ["./.fonts/install.sh", Installing Powerline Fonts]

# Git Config
- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global

# ZSH files
- link:
    ~/.zshrc: 'zsh/zshrc'
    ~/.zshenv: 'zsh/zshenv'
    ~/.oh-my-zsh: 'zsh/oh-my-zsh/'
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: 'zsh/plugins/zsh-autosuggestions'
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: 'zsh/plugins/zsh-syntax-highlighting'
    ~/.oh-my-zsh/custom/plugins/zsh-completions: 'zsh/plugins/zsh-completions'
  
# Powerline Theme Config
- link:
    ~/.oh-my-zsh/custom/themes/powerlevel10k: 'zsh/themes/powerlevel10k'
    ~/.p10k.zsh: 'zsh/themes/p10k.zsh'

# VIM Configs
- link:
    ~/.vimrc: 'vim/vimrc'
    ~/.vim_runtime: 'vim/vim_runtime'
    ~/.vim_runtime/my_configs.vim: 'vim/my_configs.vim'

# Configs
- link:
    ~/bin:
    ~/.aliases.sh: 'shell/aliases.sh'
    ~/.ipython/profile_default/ipython_config.py: 'ipython/profile_default/ipython_config.py'
    ~/.ipython/profile_default/ipython_kernel_config.py: 'ipython/profile_default/ipython_kernel_config.py'
    ~/.ipython/profile_default/startup/disable_warnings.py: 'ipython/profile_default/disable_warnings.py'
    ~/.config/terminator/config: 'config/terminator/config'
    ~/.config/parcellite/config: 'config/parcellite/parcelliterc'


# Tmux and tmuxinator configs

# - link:
#     ~/.tmux.conf: tmux.conf
#     ~/.tmux.conf.local: tmux.conf.local
#     ~/.tmuxinator: tmuxinator
# - shell:
#   #Tmux plugins
#   - ~/.tmux/plugins/tpm/bin/install_plugins; true
#   - ~/.tmux/plugins/tpm/bin/update_plugins all; true

- shell:
  - ["git submodule sync --recursive", Syncing submodule remotes]
  - ["git submodule foreach git pull origin master", Updating submodule contents]
  - ["date > ~/.dotfiles_update", Logging last update]
