" Awesome VIM Installation via https://github.com/amix/vimrc.git
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

set hidden

try
source ~/.vim_runtime/my_configs.vim
catch
endtry